### ISSUE TITLE
The strong car does not appear

### ISSUE THREAD

**Issue by Baduzinh** [qbcore-framework/qb-truckrobbery#1]
I could see why the strong car does not spawn at the marked location after starting the mission.

**Comment by jigglyblunt** [comment]
The fix for this issue simple code change on one line,
qb-truckrobbery/client
Line #285 (change with this code line below)
transport = CreateVehicle(GetHashKey('stockade'), VehicleCoords.x, VehicleCoords.y, VehicleCoords.z, 0,  0, 0, true, true)

**Comment by GhzGarage** [comment]
Fixed with commit per jigglyblunt https://github.com/qbcore-framework/qb-truckrobbery/commit/12e6b9b5a09aefcd1bb21e907510c3e9f94ea0ff#diff-6f0b2f6b34829d0f65728f2508a4f5e2ef0d39d59b554b3ec8613c8feaacf74d
