### ISSUE TITLE
Mission starts point doesn't exist in game [BUG]

### ISSUE THREAD

**Issue by Juniorr72** [qbcore-framework/qb-truckrobbery#13]
The Mission start point to try and start the mission isn't there, I've looked everywhere and can't seem to find out why. I also set the Active Police requirement to 0 for testing purpose and still nothing.

**Comment by Howsn** [comment]
I have the same problem, this only happens on my live server where I gor alot of players. When testing on dev server everything works.

**Comment by MatthewRorke** [comment]
@Juniorr72 Have you tried running `/tp 960.71197509766 -215.51979064941 76.2552947998` ?

**Comment by Juniorr72** [comment]
Location was being set to the middle of the air; Mission start needed to be set to be on the ground.
