### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SOH69** [qbcore-framework/qb-truckrobbery#17]
**Describe the bug**

So I saw that when I take the job and the car spawns, if someone else gets near the truck before i get near to it, the truck gets unregistered from my machine, I made some debugging and found that if my truck object number gets invalid if someone else gets near the truck before me. The entity does not exist in my client!

**To Reproduce**
1. Take the job
2. Dont go any near to the truck, wait there 
3. Send someone else to the truck
4. When he gets into a imaginary radius of the truck you will see the blip vanishes and you cant continue the robbery

**Expected behavior**
I cant still continue the robbery fivem is a multiplayer game.

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: 1-3 days
 - Are you using custom resource? which ones? No
 - Have you renamed `qb-` to something custom? Nope

**Additional context**

**Comment by kalivanoliveira** [comment]
maybe onesync problem?

**Comment by sinphoenix** [comment]
This issue still exist? I tried on a fresh install and everything worked fine.
