### ISSUE TITLE
Guards don't attack?

### ISSUE THREAD

**Issue by nzkfc** [qbcore-framework/qb-truckrobbery#6]
So I can do the entire script robbery, but the guards don't get out and shoot you if you aim at them or block them off. I wonder if something that controls NPC fear in QB-core is causing that?

**Comment by ihyajb** [comment]
I do know that the script currently finished but I did test and had the guards shoot at me after they had stopped the truck

**Comment by nzkfc** [comment]
Stopped the truck? If I no clip infront of the truck, they brake and just
beep, if I shoot driver the second guard switches to driver seat and beeps
haha. Maybe it's how small resources manages AI relationships or something?
Makes them calm? They def don't get out and shoot.

**Comment by pushkart2** [comment]
noclipping during a script testing is not the ideal way.. I did go through the whole script and guards shot me..

**Comment by nzkfc** [comment]
So just re-tested this, by noclip I meant TP to a location say 200m away, then get in a car and proceed to the truck.

Basically what I was expecting is, if you ram the truck, or have a weapon out near the truck then the guards would get out and shoot you, however ramming the truck does nothing, they just act like your not there, if I stand on the front of the truck and point a gun they don't do anything. If I shoot the driver, the passenger guard just takes over the wheel, if I shoot the tyres they sit there doing nothing.

Only time the guards shoot, is if you try and pull one out the truck, then they instantly try to shoot you (which is funny because the passenger shoots the driver for you as you open the door, then the passanger gets out to actually shoot)

However the entire risk of doing this job can be avoided by simply shooting the guards through the front window :S

Just figured i'd raise this as an issue? improvment even?
